---
host_description: AI experimentation and Docker services
primary_ip: 192.168.1.87
homepage_icon: nvidia.png

server_purpose:
  - AI experimentation
  - Docker host

docker_host: true
homepage_show_server: true

homepage_services:
  - group: AI
    services:
      - name: Open WebUI
        href: http://192.168.1.87:3000
        description: Local AI Interface
        status: active
        container: open-webui

      - name: Ollama
        href: http://192.168.1.87:11434
        description: RTX 4060 AI Server
        status: active
        container: ollama

      - name: Portainer Agent
        href: http://192.168.1.87:9001
        description: AI Worker Docker Agent
        status: active
        container: portainer-agent
