---
host_description: Ansible control node
primary_ip: 192.168.1.88
homepage_icon: rocky-linux.png
server_purpose:
  - Ansible Control Node
  - Git Repository
  - Automation
docker_host: false
homepage_show_server: true
