all:
  children:

    infrastructure:
      hosts:
        ubuntu-dev01:
          ansible_host: 192.168.1.86
          ansible_user: bcooke

    ai:
      hosts:
        ai-worker01:
          ansible_host: 192.168.1.87
          ansible_user: bcooke

    automation:
      hosts:
        rocky-ansible01:
          ansible_host: 192.168.1.88
          ansible_user: bcooke
          ansible_connection: local

    edge_services:
      hosts:
        edge01:
          ansible_host: 192.168.1.221
          ansible_user: bcooke
