---
- name: Deploy Homepage services configuration
  ansible.builtin.template:
    src: services.yaml.j2
    dest: "{{ homepage_config_dir }}/services.yaml"
    owner: bcooke
    group: bcooke
    mode: '0644'
  notify: Restart homepage container

- name: Deploy Homepage Docker configuration
  ansible.builtin.template:
    src: docker.yaml.j2
    dest: "{{ homepage_config_dir }}/docker.yaml"
    owner: bcooke
    group: bcooke
    mode: '0644'
  notify: Restart homepage container

- name: Deploy Homepage settings configuration
  ansible.builtin.template:
    src: settings.yaml.j2
    dest: "{{ homepage_config_dir }}/settings.yaml"
    owner: bcooke
    group: bcooke
    mode: '0644'
  notify: Restart homepage container

- name: Deploy Homepage widgets configuration
  ansible.builtin.template:
    src: widgets.yaml.j2
    dest: "{{ homepage_config_dir }}/widgets.yaml"
    owner: bcooke
    group: bcooke
    mode: '0644'
  notify: Restart homepage container

- name: Deploy Homepage bookmarks configuration
  ansible.builtin.template:
    src: bookmarks.yaml.j2
    dest: "{{ homepage_config_dir }}/bookmarks.yaml"
    owner: bcooke
    group: bcooke
    mode: '0644'
  notify: Restart homepage container
