---
- name: Deploy Homepage configuration files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ homepage_config_dir }}/{{ item.dest }}"
    owner: bcooke
    group: bcooke
    mode: "0644"
  loop:
    - { src: "services.yaml.j2",  dest: "services.yaml" }
    - { src: "docker.yaml.j2",    dest: "docker.yaml" }
    - { src: "settings.yaml.j2",  dest: "settings.yaml" }
    - { src: "widgets.yaml.j2",   dest: "widgets.yaml" }
    - { src: "bookmarks.yaml.j2", dest: "bookmarks.yaml" }
  notify: Restart homepage container

- name: Deploy Homepage Docker Compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ homepage_compose_dir }}/docker-compose.yml"
    owner: bcooke
    group: bcooke
    mode: "0644"
  notify: Redeploy Homepage
