---
homepage_owner: bcooke
homepage_group: bcooke

homepage_config_dir: /home/bcooke/docker/homepage/config
homepage_compose_dir: /home/bcooke/docker/homepage

homepage_settings:
  providers: {}

homepage_widgets:
  resources:
    cpu: true
    memory: true
    disk: /
  search:
    provider: duckduckgo
    target: _blank

homepage_bookmarks: []

homepage_docker_servers: []

homepage_container:
  service_name: homepage
  image: ghcr.io/gethomepage/homepage:latest
  container_name: homepage
  restart_policy: unless-stopped
  environment:
    HOMEPAGE_ALLOWED_HOSTS: "192.168.1.86:3000"
  ports:
    - "3000:3000"
  volumes:
    - "/home/bcooke/docker/homepage/config:/app/config"
