---
homepage_owner: bcooke
homepage_group: bcooke

homepage_config_dir: /home/bcooke/docker/homepage/config
homepage_compose_dir: /home/bcooke/docker/homepage
homepage_container: homepage

homepage_settings:
  providers: {}

homepage_widgets:
  resources:
    cpu: true
    memory: true
    disk: /
  search:
    provider: duckduckgo
    target: _blank

homepage_bookmarks: []

homepage_docker_servers: []
