---
lab_name: Abbey Root
timezone: America/Chicago
admin_user: bcooke

# Abbey internal DNS
abbey_dns_server: "{{ hostvars['edge01']['primary_ip'] }}"
abbey_dns_additional_servers: []
abbey_dns_search_domain: home.arpa
abbey_git_home: "/home/{{ admin_user }}"
abbey_git_group: "{{ admin_user }}"
abbey_git_known_hosts_mode: "0644"
abbey_git_credential_helpers: []
lab_timezone: America/Chicago
time_sync_package: chrony
time_sync_service: chronyd

abbey_git_user_name: Brad Cooke
abbey_git_user_email: brad6887@gmail.com
abbey_git_github_known_host: >-
  github.com ssh-ed25519
  AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
abbey_git_repositories:
  - name: Abbey Root
    path: "{{ abbey_git_home }}/git/abbey-root"
    origin: git@github.com:brad6887/abbey-root.git
  - name: Bread Pitt
    path: "{{ abbey_git_home }}/git/bread-pitt"
    origin: git@github.com:brad6887/bread-pitt.git
