---
- name: Check docker command
  ansible.builtin.command: docker --version
  register: docker_version
  changed_when: false

- name: Show docker version
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }}: {{ docker_version.stdout }}"

- name: Check docker service status
  ansible.builtin.systemd:
    name: docker
    state: started
  check_mode: true
  register: docker_service_check

- name: Show docker service status
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }}: Docker service is available"

- name: List running Docker containers
  ansible.builtin.command: docker ps --format "{{ '{{' }}.Names{{ '}}' }}"
  register: docker_running_containers
  changed_when: false

- name: Show running Docker containers
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} running containers: {{ docker_running_containers.stdout_lines }}"
