#!/bin/bash
#
# Abbey Root Tool: generate-command-docs.sh
#
# Purpose:
#   Generate documentation for Abbey Root command-line tools.
#
# Usage:
#   generate-command-docs.sh
#

set -e

REPO_ROOT="${ABBEY_ROOT:-$HOME/git/abbey-root}"
TOOLS_DIR="$REPO_ROOT/tools"
OUTPUT_DIR="$REPO_ROOT/docs/generated"
OUTPUT_FILE="$OUTPUT_DIR/abbey-commands.md"

mkdir -p "$OUTPUT_DIR"

{
  echo "# Abbey Root Commands"
  echo
  echo "Generated: $(date)"
  echo
  echo "This file is automatically generated from command headers in:"
  echo
  echo "\`\`\`text"
  echo "tools/"
  echo "\`\`\`"
  echo
  echo "---"
  echo

  for tool in "$TOOLS_DIR"/abbey-*; do
    [ -f "$tool" ] || continue
    [ -x "$tool" ] || continue

    command_name="$(basename "$tool")"

    purpose="$(
      awk '
        /^# Purpose:/ { in_purpose=1; next }
        /^# Usage:/ { in_purpose=0 }
        in_purpose && /^#/ {
          sub(/^# */, "")
          if (length($0) > 0) print
        }
      ' "$tool" | sed 's/^ *//'
    )"

    usage="$(
      awk '
        /^# Usage:/ { in_usage=1; next }
        /^#$/ && in_usage { exit }
        in_usage && /^#/ {
          sub(/^# */, "")
          if (length($0) > 0) print
        }
      ' "$tool" | sed 's/^ *//'
    )"

    echo "## $command_name"
    echo

    if [ -n "$purpose" ]; then
      echo "$purpose"
      echo
    fi

    if [ -n "$usage" ]; then
      echo "Usage:"
      echo
      echo "\`\`\`bash"
      echo "$usage"
      echo "\`\`\`"
      echo
    fi
  done
} > "$OUTPUT_FILE"

echo "Generated $OUTPUT_FILE"
